### PR TITLE
Try to add SoraLink crowd bypass

### LINKED ISSUE #193: Soralink Template
`https://movieku.org/replicas-subtitle-indonesia/`

### PR DESCRIPTION
**Pull request by ikancupang**
Try to resolve #193
Because SoraLink uses backend validation, I'm trying to add SoraLink crowd bypass.
@timmyRS please help improve this script.

### CODE REVIEW

**Comment by timmyRS** [comment]
My hope was to crack the code, but I guess crowd bypass is the way to go since no one seems to have cracked the code yet and I'm too apathetic.

**Comment by ikancupang** [comment]
Crack the code is difficult, because every SoraLink sites uses a different secret key.

**Comment by ikancupang** [comment]
I think it's better to use this in the background
```ruby
if(url.host.substr(0,4)=="www.")
{
	url.host=url.host.substr(4)
}
```
because SoraLink sites which uses www subdomain like this #599 doesn't work.

**Comment by timmyRS** [comment]
I've fixed this in the crowd bypass backend.

**Pull request merged**
