### PR TITLE
Add gsu.st bypass

### PR DESCRIPTION
**Pull request by ikancupang**
#507

### CODE REVIEW

**Comment by timmyRS** [comment]
This doesn't work.

**Comment by ikancupang** [comment]
Have you tried it?
I've tried it before create a pull request and it works.
reCAPTCHA checkbox at `gsu.st` is useless, just click the submit button then it will lead to `agdd5br.com`.

**Comment by timmyRS** [comment]
I see, but your bypass doesn't press the submit button, which is why it didn't work.

**Comment by ikancupang** [comment]
I just directly call the submit function.

**Pull request closed without merging**
