### PR TITLE
bluemediafiles.com bypass

### PR DESCRIPTION
**Pull request by akuankka128**

### CODE REVIEW

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by akuankka128** [comment]
> Could you provide an example link?

http://bluemediafiles.com/creatinglinks2BhAUwzDg32BCq82B2tAuvz2BQrs2nXgDxsV65EpFkfoibAknyxbwrt25OUY?xurl=s://docs.google.com/uc?id=0Bxe0FKfS1vPtMHE4NE1zdmJCOWs&export=download

**Comment by timmyRS** [comment]
This is already bypassed.

**Comment by akuankka128** [comment]
Hmm, I wonder why it didn't trigger for me then..

**Comment by timmyRS** [comment]
Which browser are you using?

**Comment by akuankka128** [comment]
Chrome

**Comment by timmyRS** [comment]
Using 12.6 on Chrome also works for me. Have you verified that Universal Bypass in general works?
- https://universal-bypass.org/firstrun
- https://universal-bypass.org/example-links

**Comment by akuankka128** [comment]
Sorry for late response.

Yes, Universal Bypass does work perfectly in general.
Yesterday the bluemediafiles.com bypass didn't work at all, now it does, but slowly, my bypass seems a lot faster (at least for slower connections) as it doesn't require the DOM to load.

**Pull request closed without merging**
