### PR TITLE
Bypass gixen.com timer

### PR DESCRIPTION
**Pull request by FailedShack**
Bypasses 20 second timer shown to free users that log into the site.

### CODE REVIEW

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by FailedShack** [comment]
The bypass is only scheduled to run on: https://www.gixen.com/home_1.php
Which is shown right after clicking "Log in Now". You would need to create an account.

**Comment by timmyRS** [comment]
I don't see that being useful in Universal Bypass itself, but you can keep that as a custom bypass, if you want.

**Comment by FailedShack** [comment]
Timer

Here's what I was talking about. I've only used the site a couple times but I do know that it is fairly well known tool to schedule bids on eBay.

I know it's not an URL shortener but I find it equally annoying and given that the motto of this extension is literally `Don't waste your time with compliance.`, I thought it would be a good fit.
I understand if you feel it's out of scope, though.

**Pull request merged**
