### PR TITLE
howdyho.net download timer bypass

### PR DESCRIPTION
**Pull request by timas130**

### CODE REVIEW

**Comment by timmyrs** [comment]
Could you provide an example link?

**Comment by timas130** [comment]
https://howdyho.net/download/479

**Comment by timas130** [comment]
Just https://howdyho.net/download/[insert a number here]

**Comment by timmyrs** [comment]
This can't be bypassed because they're verifying that you've actually waited in the backend, and as such your code also doesn't work.

**Comment by timas130** [comment]
I got that! It just checks the `referer` header.

**Comment by timmyrs** [comment]
It also realises you haven't waited if the referrer header is set.

**Pull request closed without merging**
