### PR TITLE
zt-protect.com bypass

### PR DESCRIPTION
**Pull request by JohnTitor2036**

### CODE REVIEW

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by JohnTitor2036** [comment]
Sure : [https://zt-protect.com/to/R1FYSVB1KzBtSThjRlEvdS9xUkljM0hrUUFPWi9OVXdjaW8wVFBqbDVxOGppNXErRGZuRmVkSmM3N3lQQTVwUg==](https://zt-protect.com/to/R1FYSVB1KzBtSThjRlEvdS9xUkljM0hrUUFPWi9OVXdjaW8wVFBqbDVxOGppNXErRGZuRmVkSmM3N3lQQTVwUg==)

**Comment by JohnTitor2036** [comment]
It didn't work ?

**Comment by timmyRS** [comment]
Have you updated to 5f6ff80?

**Comment by JohnTitor2036** [comment]
Ho my mistake, I thought you had canceled the merger request, thanks :)

**Pull request closed without merging**
