### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by DineshSolanki**
reduced delay & fixed button click not working

### CODE REVIEW

**Comment by DineshSolanki** [comment]
please commit this, it works more efficiently.

**Comment by timmyRS** [comment]
Use 3d4ed2f.

**Comment by DineshSolanki** [comment]
> 
> 
> Use [3d4ed2f](https://github.com/timmyRS/Universal-Bypass/commit/3d4ed2fa14c4e658cc9016cdfba44109d57b1d04).

okay, makes sense, sorry new to universal Bypass.

**Comment by timmyRS** [comment]
No problem, I should've said something, but I didn't merge your original PR and instead made that commit.

**Pull request closed without merging**
