### PR TITLE
add boost.ink bypass

### PR DESCRIPTION
**Pull request by orasunis**
Hello TimmyRS,
I want you to merge this bypass for the benefit of the whole society.
I know that you own this website, but I know the perfect solution to convince you to add this bypass.
If you won't merge the changes, I will simply call an antitrust lawyer as that would be an unfair business practice!
I am sure you will accept my offer,
thanks for the attention.

### CODE REVIEW

**Comment by niklasbuesing** [comment]
There is now an extension to skip boost.ink: [Boost.ink Skipper](https://chrome.google.com/webstore/detail/boostink-skipper/cihemednabkhbhmnjghjjnmgilbjjhkh/)

**Comment by timmyrs** [comment]
I'll add a bypass the minute Universal Bypass' profits exceed Boost.ink's. You might not be aware, but in this society you need money to survive.

**Comment by SenkJu** [comment]
Other sites also need money too, which they don't get because of your extension. Why make an exception for yourself?

**Comment by Pascaloli** [comment]
Because hes poor lol

**Comment by timmyrs** [comment]
Universal Bypass provides bypasses for countless of annoying and heartless websites, all for free. I'd like to think that Boost.ink is a rather nice website, we actually invested the time to make it look and feel nice. Now, you can accept that Boost.ink's revenue supports the free extension you are using at the price that Boost.ink is not bypassed, or you don't use it. Easy.

**Comment by SenkJu** [comment]
Do you really think all pages that are automatically skipped by your extensions are "heartless"? Not everyone has the time or resources to make their own page. Also, your extension definitely didn't just skip pages that you might call annoying. She did it with ours, too, until I fixed it. It was in no way penetrating or intrusive. It only contains two Adsense advertising blocks, no popups, no viruses, nothing that could affect the user experience in any way. The only reason you whitelisted your own site is because you don't want to do the damage you do to other sites to yourself.

**Comment by timmyrs** [comment]
I also wouldn't add a feature where Universal Bypass would self-uninstall, because Boost.ink is what is financing Universal Bypass' developement.

**Comment by SenkJu** [comment]
Maybe the financing of your project should not be based on exactly what it wants to fight.

**Pull request closed without merging**
