### PR TITLE
Added support for 4snip.pw

### PR DESCRIPTION
**Pull request by GiuseppeCesarano**

### CODE REVIEW

**Comment by timmyrs** [comment]
4snip.pw is already bypassed by crowd bypass, and I won't programmatically press a captcha button.

**Comment by GiuseppeCesarano** [comment]
It doens't get bypassed by crowd bypass;
https://4snip.pw/out/5egfwDH586zeaEaw2a5GEPorzXFFoiq00Tl7ILc3zEFj_ppl_DezgnpDR3pxveLi2tsw
And the script doesn't press the captcha button

**Comment by timmyrs** [comment]
Still, this is prone to issues. The user can spare the click so they won't have any captcha issues.

**Comment by timmyrs** [comment]
Huh, 4snip doesn't seem to be using the template it seems to be using.

**Comment by GiuseppeCesarano** [comment]
I noticed that too, the tags id are confused at the best, I'm running an automated test there is no captcha going on there

**Comment by timmyrs** [comment]
Yeah, I've added a bypass in 9.2.

**Pull request closed without merging**
